inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/setup
    - bin/spring
    
Style/BlockDelimiters:
  Exclude:
    - spec/**/*
    
Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - config/puma.rb

Style/SpaceAroundOperators:
  Exclude:
    - config/puma.rb