# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41c57ecab9ae7ae8460a775ecb686a7d65449b307d4c46aaad676203c696046d3e9b93631877780c7f8b487f3b0d2497094f3ef350511da65d28e09b2544929c

test:
  secret_key_base: ed8bd435696c3e93c6ae67c973f5aaca198184186616b23b5a5e79a4f6e62d36bf99c53abb8844debaf572628664d7c4dc7385429fe92ef1d773672289943d1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
